name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: echo event
        run: |
          gh api repos/lackhoa/ex1/actions/runs \
              --jq '.workflow_runs.[].compare(.head_commit.id == "${{ env.HEAD_COMMIT_ID }}")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_COMMIT_ID: ${{ toJSON(github.event.head_commit).id }}
