name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        uses: echo "X=2" >> $GITHUB_ENV
      - name: echo env
        uses: echo $X
    outputs:
      X: ${{ env.X }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - echo ${{ needs.build.outputs.X }}
