name: Test workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      gha_skip_deps:
        description: '(Unsafe) Skip dependencies compilation: `true` / `false`'
        required: true
        default: 'false'
      gha_rebuild_deps:
        description: 'Rebuild dependencies without cache: `true` / `false`'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: |
        echo ${{github.event.head_commit.message}}


    - name: multiline
      run: |
        echo "X=${{ true &&
                    (false &&
                     true) }}" >> ${GITHUB_ENV}

    - name: use x
      run: echo $X
