name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: ${{ true == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      if: false
      with:
        token: ${{ secrets.PAT }}

    - name: tar one
      run: |
        touch a
        touch b
        GZIP=-n tar -czf ab.tar.gz a b
        sha1sum ab.tar.gz

    - name: tar two
      run: |
        touch a
        touch b
        GZIP=-n tar -czf ab-two.tar.gz a b
        sha1sum ab-two.tar.gz
