name: main

on:
  push:
    branches: ['**']

jobs:
  # one:
  #   name: one
  #   uses: ./.github/workflows/one.yaml
  # two:
  #   name: two
  #   uses: ./.github/workflows/two.yaml
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3

    - name: Install aws-amicleaner
      run: go install github.com/trussworks/truss-aws-tools/...

    - name: ls
      run: ls ~/go/bin/

    - name: something else
      run: |
        echo running ami-cleaner
        ami-cleaner

        echo ~/go/bin/ami-cleaner
        ~/go/bin/ami-cleaner
