name: main

on:
  push:
    branches: ['**']

jobs:
  one:
    name: one
    uses: ./.github/workflows/one.yaml
  two:
    name: two
    uses: ./.github/workflows/two.yaml
  main:
    runs-on: ubuntu-latest
    steps:
    - run: wc -c <(echo ${{ secrets.PAT }})
