name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  a:
    matrix:
      runs-on: ['ubuntu-latest']
    runs-on: ${{ matrix.runs-on }}
    if: false
    steps:
      -
      - run echo ${{ github.workspace }}
