name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.4"
    - name: Hello world
      run: kustomize
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: do something
      run: echo ${GITHUB_SHA::8}
    - name: try docker-compose
      run: docker-compose --version
