name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: val
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: echo
      run: echo "Hello world" > /tmp/hello
    - name: hash
      run: echo $(sha1sum /tmp/hello)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo ${{ needs.build.outputs.key }}
