name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: |
        export A=1

    - name: Step 1
      run: |
        export X=1
        echo X=${X} >> ${GITHUB_ENV}
        echo ${{ env.X }}

    - name: Step 2
      run: |
        echo ${A}
        echo ${{ env.A }}
        echo ${X}
        echo ${{ env.X }}
