name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: ${{ true == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      if: false
      with:
        token: ${{ secrets.PAT }}
    - name: echo
      run: echo "Hello world" > /tmp/hello
    - name: hash
      run: echo $(sha1sum /tmp/hello)
