name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    strategy:
      matrix:
        name: [one, two]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        if: matrix['name'] == one
        uses: actions/checkout@v2

      - name: Install botocore
        run: ./test.sh
