name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  a:
    runs-on: 'macos-11'
    steps:
      - run: brew install --cask android-commandlinetools
      - run: |
          export PATH=/opt/android-sdk/cmdline-tools/latest/bin:$PATH
          (while sleep 3; do echo "y"; done) | sdkmanager --licenses
