name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    strategy:
      matrix:
        name: [one, two]
        one-value: [ '1' ]
        two-value: [ '2' ]
    if: matrix.name == 'one'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: echo 1 or 2
        run: echo ${{ matrix[format('{0}-value', matrix.name)] }}

      - name: echo matrix name
        run: echo $MATRIX_NAME
