name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: echo "X=2" >> $GITHUB_ENV
      - uses: echo $X
    outputs:
      X: ${{ env.X }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.X }}
