name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  more:
    runs-on: ubuntu-latest
    if: |
      true
      || (true

      && false)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: echo matrix name
        env:
          X: We are great!
        run: "./test.sh"

  even-more:
    runs-on: ubuntu-latest
    if: |
      (true
      || true)

      && false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: echo matrix name
        env:
          X: We are great!
        run: "./test.sh"



  build:
    runs-on: ubuntu-latest
    if: |
      true
      || true

      && true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: echo matrix name
        env:
          X: We are great!
        run: "./test.sh"
