name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "X=2" >> $GITHUB_ENV
      - run: echo $X
    outputs:
      X: ${{ env.X }}

  deploy:
    needs: build
    if: true
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.build.outputs.X }}
