name: Main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: ls this-file-does-not-exist
      - run: echo This still runs!
        if: always()
