name: main

on:
  push:
    branches: ['**']

jobs:
  # one:
  #   name: one
  #   uses: ./.github/workflows/one.yaml
  # two:
  #   name: two
  #   uses: ./.github/workflows/two.yaml
  main:
    needs: [one, two]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Install aws-amicleaner
      run: go get -u github.com/trussworks/truss-aws-tools/...

    - name: Cleanup old AMIs
      run: |
        ami-cleaner --unused --region "$REGION" --days=30 -D \
        --tag-key="AmiType" --tag-value="ubuntu-amd64-eks-nvidia-wine"
