name: Main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ contains('onetwo', 'hello') }}
      - run: echo ${{ contains('onetwo', 'net') }}
