name: Test workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      gha_skip_deps:
        description: '(Unsafe) Skip dependencies compilation: `true` / `false`'
        required: true
        default: 'false'
      gha_rebuild_deps:
        description: 'Rebuild dependencies without cache: `true` / `false`'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master for reference
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Check whether current commit is from master
        run: git merge-base --is-ancestor HEAD master
