name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: making files
        run: |
          mkdir dir
          mkdir dir/d
          touch dir/d/a
