name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  call-workflow-1:
    uses: lackhoa/ex1/.github/workflows/two.yaml@172239021f7ba04fe7327647b213799853a9eb89
