name: Main

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GH | jq
        env:
          GH: ${{ toJSON(github) }}
