name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    strategy:
      matrix:
        name: [one, two]
        one-value: '1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: echo one
        run: echo ${{ matrix[joint([matrix['name'], value], '-')] }}
