name: Main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  build:
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 5

  test:
    needs: build
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ (github.event.inputs.empty_ccache == 'true')
                   || (github.event_name == 'schedule')
                   || (env.BUILD_DEPS == 'true') }}
