name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: ${{ true == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: try out action
      uses: lackhoa/ex1/.github/actions/glow-builder-common@${{ github.ref }}
