name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: echo Hello world

    - name: Step 1
      run:
        echo This runs
        cat file-that-does-not-exist
        echo This will never run  # Execution won't reach here

    - name: Step 2
      run: echo This will never run  # Step is skipped

    - name: Step 3
      if: always()
      run: echo I always run  # This step runs because of the special `if` key
