name: main

on:
  push:
    branches: ['**']

jobs:
  one:
    name: one
    uses: ./.github/workflows/one.yaml
  two:
    name: two
    uses: ./.github/workflows/two.yaml
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifacts@v3
      with:
        name: one
    - uses: actions/download-artifact@v3
      with:
        name: two
    - run: ls -lR
