name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: pwd
      run: pwd
    - name: hash
      run: echo ${{ hashFiles('/home/runner/work/ex1/ex1') }}
