name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: pwd
      run: echo "Hello world" > /tmp/hello
    - name: hash
      run: echo ${{ hashFiles('/tmp/hello') }}
