name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  a:
    runs-on: 'macos-11'
    steps:
      - run: echo hello > /tmp/hello.txt
      - name: Upload sysroot to Github Actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: glow-dependencies-sysroot
          path: /private/tmp/hello.txt
          retention-days: 14
