name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  strategy:
    matrix:
      name: [one, two]
  build:
    if: matrix['name'] == one
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install botocore
        run: ./test.sh
