name: Test workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      gha_skip_deps:
        description: '(Unsafe) Skip dependencies compilation: `true` / `false`'
        required: true
        default: 'false'
      gha_rebuild_deps:
        description: 'Rebuild dependencies without cache: `true` / `false`'
        required: true
        default: 'false'

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: sha1sum
        run: echo hello | sha1sum | cut -f 1 -d ' '

  deploy:
    needs: build
    if: (needs.build.result == 'skipped') || (needs.build.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "${{ toJSON(needs.build) }}"
