name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: ${{ true == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      if: false
      with:
        token: ${{ secrets.PAT }}

    - name: one
      run: export X=1

    - name: two
      run: echo $X
