name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  a:
    timeout-minutes: ${{ 5 }}
    runs-on: 'macos-11'
    steps:
    - uses: actions/checkout@v2

    - name: Setup tmate session
      if: failed()
      uses: mxschmitt/action-tmate@v3

