name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  a:
    timeout-minutes: ${{ fromJSON('{true: 5; false: 10}')[true] }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3

