name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  more:
    runs-on: ubuntu-latest
    if: |
      true
      || (true

      && false)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - env:
          X: We are great!
        run: echo ${{ env.X  }}
