name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: |
        sudo echo hello world
