name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      key: ${{ true == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - uses: actions/create-outputs@v0.0.0-fake
      id: test

    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        output: |
          {"summary":${{ steps.test.outputs.summary }}}
