name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: echo Hello world

    - name: Step 1
      run: exit 1

    - name: Step 2
      run: echo This will never run

    - name: Step 3
      if: always()
      run: echo This still runs
