name: Test workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: echo Hello world # Echoes 'Hello world'

    - name: Step 1
      run: |
        echo This runs                # Echoes 'This run'
        cat file-that-does-not-exist  # 'cat: file-that-does-not-exist: No such file or directory'
        echo This will never run      # Execution won't reach here

    - name: Step 2
      run: echo This will never run  # Step is skipped because one of the previous steps fail

    - name: Step 3
      if: |
        ${{ true
            || false}}
      run: echo I always run  # Echoes 'I always run' step runs because of the special `if` key
