name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: gha API
        run: |
          export HEAD_COMMIT_ID=${{ toJSON(github.event.head_commit.id) }}
          gh api repos/lackhoa/ex1/actions/runs | jq '
              .workflow_runs[]
              | select(.head_commit.id == env.HEAD_COMMIT_ID)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
