name: Main

env:
  X: 5

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  runs-on: ubuntu-latest
  a:
    if: false
    steps:
    - run: echo hello

b:
  runs-on: ubuntu-latest
  needs:
    - a
  if: needs.a.result != 'skipped'
  steps:
  - run: echo goodbye
