name: Main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'hello world'

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y apksigner
      - run: apksigner --help
