name: Test workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      if: false
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Step 0
      run: |
        echo ${{github.event.head_commit.message}}


    - name: multiline
      run: |
        echo ${{ true ||
                 false &&
                 true  }}
