name: workflow_run triggered

on:
  check_suite:
    types: [completed]

jobs:
  a:
    name: main-a
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ toJSON(github.event.check_suite) }}"
