name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: echo event
        run: |
          echo "${HEAD_COMMIT}"
        env:
          HEAD_COMMIT: ${{ toJSON(github.event.head_commit) }}
