name: Main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: gha API
        run: |
          gh api repos/lackhoa/ex1/actions/runs | jq --arg HEAD_COMMIT_ID "$HEAD_COMMIT_ID" '
              .workflow_runs[]
              | select(.head_commit.id == "$HEAD_COMMIT_ID")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_COMMIT_ID: ${{ toJSON(github.event.head_commit.id) }}
