name: one

on:
  push:
  workflow_call:
    inputs:
      x:
        default: '5'
        required: false

jobs:
  a:
    name: one-a
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON(inputs) }}"
