name: one

on:
  workflow_call:

jobs:
  a:
    name: one-a
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > hello.txt
    - uses: actions/upload-artifacts@v3
      with:
        name: one
        path: .
