name: one

on:
  push:
  workflow_call:
    inputs:
      x:
        default: false
        required: false
        type: boolean

jobs:
  a:
    name: one-a
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON(inputs.x) }}"
