name: Two

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: making files
        run: |
          mkdir dir
          mkdir dir/d
          touch dir/d/a

      - name: github actions API
        run: |
          curl \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Hatch-Arcade/ex1/actions/runs | jq

