name: Two

permissions:
  actions: write

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh workflow run main.yaml -f message='hello from cronjob'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
