name: Two

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: github actions API
        run: |
          gh api repos/lackhoa/ex1/actions/runs?per_page=1 --jq '.workflow_runs.[].id'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
