name: two

on:
  workflow_call:

jobs:
  a:
    name: two-a
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > hello.txt
    - uses: actions/upload-artifact@v3
      with:
        name: two
        path: .
