name: Two

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: github actions API
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" \
              --title "$(git show --no-patch --format=%s)" \
          # gh api repos/Hatch-Arcade/hatch-gl-streaming/actions/runs?per_page=1 --jq '.workflow_runs.[].id'

